name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # Тепер AdoptOpenJDK є частиною Adoptium

      # Кешування залежностей Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Де зберігаються кешовані залежності Maven
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Генерація унікального ключа на основі файлів pom.xml
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify


